packages:
  - packages/*
  - examples/*
updateConfig:
  ignoreDependencies:
    - p-throttle
    - eslint
catalog:
  '@ai-sdk/openai': ^1.3.1
  '@apidevtools/swagger-parser': ^10.1.1
  '@dexaai/dexter': ^4.1.1
  '@e2b/code-interpreter': ^1.0.4
  '@fisch0920/eslint-config': ^1.4.0
  '@langchain/core': ^0.3.43
  '@langchain/openai': ^0.4.9
  '@mastra/core': ^0.6.4
  '@modelcontextprotocol/sdk': ^1.7.0
  '@nangohq/node': 0.42.22 # pinned for now
  '@total-typescript/ts-reset': ^0.6.1
  '@types/jsrsasign': ^10.5.15
  '@types/node': ^22.13.13
  '@xsai/tool': ^0.1.3
  ai: ^4.2.2
  bumpp: ^10.1.0
  camelcase: ^8.0.0
  cleye: ^1.3.4
  decamelize: ^6.0.0
  dedent: ^1.5.3
  del-cli: ^6.0.0
  delay: ^6.0.0
  dotenv: ^16.4.7
  duck-duck-scrape: ^2.2.7
  eslint: 8.57.1 # pinned to v8 until we can upgrade to the new config format in v9
  execa: ^9.5.2
  exit-hook: ^4.0.0
  fast-xml-parser: ^5.0.9
  genkit: ^1.3.0
  genkitx-openai: ^0.20.2
  json-schema-to-zod: ^2.6.0
  jsonrepair: ^3.12.0
  jsrsasign: ^10.9.0
  ky: ^1.7.5
  langchain: ^0.3.19
  lint-staged: ^15.5.0
  llamaindex: ^0.9.12
  mathjs: ^13.2.3
  npm-run-all2: ^7.0.2
  octokit: ^4.1.2
  only-allow: ^1.2.1
  openai: ^4.89.0
  openai-fetch: ^3.4.2
  openai-zod-to-json-schema: ^1.0.3
  openapi-types: ^12.1.3
  p-map: ^7.0.3
  p-throttle: 6.2.0 # pinned for now
  prettier: ^3.5.3
  restore-cursor: ^5.1.0
  simple-git-hooks: ^2.12.1
  string-strip-html: ^13.4.12
  syncpack: 14.0.0-alpha.10
  tsup: ^8.4.0
  tsx: ^4.19.3
  turbo: ^2.4.4
  twitter-api-sdk: ^1.2.1
  type-fest: ^4.38.0
  typescript: ^5.8.2
  vitest: ^3.0.9
  wikibase-sdk: ^10.2.2
  xsai: ^0.1.3
  zod: ^3.24.2
  zod-validation-error: ^3.4.0
  zoominfo-api-auth-client: ^1.0.1
