packages:
  - packages/*
  - examples/*
updateConfig:
  ignoreDependencies:
    - p-throttle
    - '@nangohq/node'
catalog:
  '@ai-sdk/openai': ^1.3.22
  '@apidevtools/swagger-parser': ^10.1.1
  '@dexaai/dexter': ^4.1.1
  '@e2b/code-interpreter': ^1.5.0
  '@fisch0920/config': ^1.1.0
  '@googleapis/customsearch': ^3.2.0
  '@langchain/core': ^0.3.57
  '@langchain/openai': ^0.5.11
  '@mastra/core': ^0.10.0
  '@modelcontextprotocol/sdk': ^1.12.0
  '@nangohq/node': 0.42.22 # pinned for now
  '@types/jsrsasign': ^10.5.15
  '@types/node': ^22.15.21
  '@xsai/tool': ^0.3.0-beta.2
  ai: ^4.3.16
  bumpp: ^10.1.1
  camelcase: ^8.0.0
  cleye: ^1.3.4
  decamelize: ^6.0.0
  dedent: ^1.6.0
  del-cli: ^6.0.0
  delay: ^6.0.0
  dotenv: ^16.5.0
  duck-duck-scrape: ^2.2.7
  eslint: ^9.27.0
  execa: ^9.6.0
  exit-hook: ^4.0.0
  fast-xml-parser: ^5.2.3
  genkit: ^1.10.0
  genkitx-openai: ^0.22.3
  google-auth-library: ^9.15.1
  googleapis: ^149.0.0
  json-schema-to-zod: ^2.6.1
  jsonrepair: ^3.12.0
  jsrsasign: ^10.9.0
  ky: ^1.8.1
  langchain: ^0.3.27
  lint-staged: ^16.0.0
  llamaindex: ^0.11.3
  mathjs: ^13.2.3
  npm-run-all2: ^8.0.4
  octokit: ^5.0.2
  only-allow: ^1.2.1
  openai: ^4.103.0
  openai-fetch: ^3.4.2
  openai-zod-to-json-schema: ^1.0.3
  openapi-types: ^12.1.3
  p-map: ^7.0.3
  p-throttle: 6.2.0 # pinned for now
  prettier: ^3.5.3
  restore-cursor: ^5.1.0
  simple-git-hooks: ^2.13.0
  string-strip-html: ^13.4.12
  syncpack: 14.0.0-alpha.10
  tsup: ^8.5.0
  tsx: ^4.19.4
  turbo: ^2.5.3
  twitter-api-sdk: ^1.2.1
  type-fest: ^4.41.0
  typescript: ^5.8.3
  vitest: ^3.1.4
  wikibase-sdk: ^10.2.3
  xsai: ^0.3.0-beta.2
  zod: ^3.25.30
  zod-validation-error: ^3.4.1
  zoominfo-api-auth-client: ^1.0.1
